### ISSUE TITLE
Cursos pendientes por realizar 

### ISSUE THREAD

**Issue by IngWennuis** [IngWennuis/proyecto#2]
- [x] [GIT+GitHub: Todo un sistema de control de versiones de cero](https://fernando-herrera.com/#/curso/git-github)
- [ ] [#1 – JavaScript Moderno: Guía para dominar el lenguaje](https://fernando-herrera.com/#/curso/js-moderno)
- [ ] [#2 – REACT: DE CERO A EXPERTO ( HOOKS Y MERN )](https://fernando-herrera.com/#/curso/react)
- [ ] [#3 – REACT NATIVE: APLICACIONES NATIVAS PARA IOS Y ANDROID](https://fernando-herrera.com/#/curso/react-native)
- [ ] [#4 – REACT PRO: Lleva tus bases al siguiente nivel](https://fernando-herrera.com/#/curso/react-native)
- [ ] [#5 – Node: De cero a experto](https://fernando-herrera.com/#/curso/node-cero-experto)
- [ ] [#6 – ReactiveX – RxJs: De cero hasta los detalles](https://fernando-herrera.com/#/curso/rxjs)
